export const DEFAULT_PROJECT_EVENT_SCHEDULE_MAX_SCHEDULES = 128;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_MAX_WATCHES = 64;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_PROMPT_MAX_BYTES = 32_768;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_MAX_HORIZON_MS = 30 * 24 * 60 * 60_000;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_LATE_GRACE_MS = 24 * 60 * 60_000;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_DELIVERY_TTL_MS = 24 * 60 * 60_000;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_SWEEP_BATCH_SIZE = 20;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_CLAIM_LEASE_MS = 60_000;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_RETRY_BASE_MS = 30_000;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_MAX_ATTEMPTS = 8;
export const DEFAULT_PROJECT_EVENT_SCHEDULE_MAX_DEFERRAL_MS = 24 * 60 * 60_000;
export const DEFAULT_PROJECT_EVENT_WATCH_COOLDOWN_MIN_MS = 60_000;
/** Finite execution count controls cost without promising a monetary budget. */
export const DEFAULT_PROJECT_EVENT_WATCH_MAX_EXECUTIONS = 100;
export const DEFAULT_PROJECT_EVENT_WATCH_MAX_CONCURRENT = 3;
