import type { ProjectEventLimits } from '../types/project-events';

export const DEFAULT_PROJECT_EVENT_MAX_ACTIVE_SUBSCRIPTIONS_PER_PROJECT = 200;
export const DEFAULT_PROJECT_EVENT_FILTER_MAX_VALUES_PER_FIELD = 20;
export const DEFAULT_PROJECT_EVENT_FILTER_MAX_MATCH_KEYS = 100;
export const DEFAULT_PROJECT_EVENT_FILTER_MAX_STRING_BYTES = 160;
export const DEFAULT_PROJECT_EVENT_METADATA_MAX_BYTES = 8192;
export const DEFAULT_PROJECT_EVENT_METADATA_MAX_DEPTH = 4;
export const DEFAULT_PROJECT_EVENT_METADATA_MAX_KEYS = 64;
export const DEFAULT_PROJECT_EVENT_METADATA_MAX_ARRAY_ITEMS = 64;
export const DEFAULT_PROJECT_EVENT_DISPLAY_MAX_BYTES = 4096;
export const DEFAULT_PROJECT_EVENT_DISPLAY_MAX_LABELS = 12;
export const DEFAULT_PROJECT_EVENT_RAW_PAYLOAD_REF_MAX_BYTES = 512;
export const DEFAULT_PROJECT_EVENT_REASON_MAX_BYTES = 1024;
export const DEFAULT_PROJECT_EVENT_MAX_MATCHES_PER_EVENT = 100;
export const DEFAULT_PROJECT_EVENT_DELIVERY_BATCH_MAX_EVENTS = 50;
export const DEFAULT_PROJECT_EVENT_DELIVERY_ATTEMPT_MAX_PER_BATCH = 10;
export const DEFAULT_PROJECT_EVENT_LIST_LIMIT = 50;
export const DEFAULT_PROJECT_EVENT_LIST_MAX = 200;
export const DEFAULT_PROJECT_EVENT_RECENT_STATUS_LIMIT = 50;
export const DEFAULT_PROJECT_EVENT_RETENTION_DAYS = 30;
export const DEFAULT_PROJECT_EVENT_RETENTION_BATCH_ROWS = 500;

export const DEFAULT_PROJECT_EVENT_LIMITS: ProjectEventLimits = {
  maxActiveSubscriptionsPerProject: DEFAULT_PROJECT_EVENT_MAX_ACTIVE_SUBSCRIPTIONS_PER_PROJECT,
  maxFilterValuesPerField: DEFAULT_PROJECT_EVENT_FILTER_MAX_VALUES_PER_FIELD,
  maxFilterMatchKeysPerSubscription: DEFAULT_PROJECT_EVENT_FILTER_MAX_MATCH_KEYS,
  maxFilterStringBytes: DEFAULT_PROJECT_EVENT_FILTER_MAX_STRING_BYTES,
  maxMetadataBytes: DEFAULT_PROJECT_EVENT_METADATA_MAX_BYTES,
  maxMetadataDepth: DEFAULT_PROJECT_EVENT_METADATA_MAX_DEPTH,
  maxMetadataKeys: DEFAULT_PROJECT_EVENT_METADATA_MAX_KEYS,
  maxMetadataArrayItems: DEFAULT_PROJECT_EVENT_METADATA_MAX_ARRAY_ITEMS,
  maxDisplayBytes: DEFAULT_PROJECT_EVENT_DISPLAY_MAX_BYTES,
  maxDisplayLabels: DEFAULT_PROJECT_EVENT_DISPLAY_MAX_LABELS,
  maxRawPayloadRefBytes: DEFAULT_PROJECT_EVENT_RAW_PAYLOAD_REF_MAX_BYTES,
  maxReasonBytes: DEFAULT_PROJECT_EVENT_REASON_MAX_BYTES,
  maxMatchesPerEvent: DEFAULT_PROJECT_EVENT_MAX_MATCHES_PER_EVENT,
  maxDeliveryBatchEvents: DEFAULT_PROJECT_EVENT_DELIVERY_BATCH_MAX_EVENTS,
  maxAttemptsPerBatch: DEFAULT_PROJECT_EVENT_DELIVERY_ATTEMPT_MAX_PER_BATCH,
  listLimitDefault: DEFAULT_PROJECT_EVENT_LIST_LIMIT,
  listLimitMax: DEFAULT_PROJECT_EVENT_LIST_MAX,
  recentStatusLimit: DEFAULT_PROJECT_EVENT_RECENT_STATUS_LIMIT,
  retentionDays: DEFAULT_PROJECT_EVENT_RETENTION_DAYS,
  retentionBatchRows: DEFAULT_PROJECT_EVENT_RETENTION_BATCH_ROWS,
};
