export const DEFAULT_PROJECT_EVENT_CHANNEL_MAX_CHANNELS = 128;
export const DEFAULT_PROJECT_EVENT_CHANNEL_MESSAGE_MAX_BYTES = 4096;
export const DEFAULT_PROJECT_EVENT_CHANNEL_NAME_MAX_BYTES = 64;
export const DEFAULT_PROJECT_EVENT_CHANNEL_PUBLISH_WINDOW_MS = 60_000;
export const DEFAULT_PROJECT_EVENT_CHANNEL_PUBLISH_MAX_PER_WINDOW = 120;
export const DEFAULT_PROJECT_EVENT_CHANNEL_CURSOR_TTL_MS = 3_600_000;
export const DEFAULT_PROJECT_EVENT_CHANNEL_CATALOG_IDLE_TTL_MS = 30 * 24 * 60 * 60 * 1000;
