import type { EvidenceRequirement } from './evidence';
import type {
  AllocationEntrypointInventoryEntry,
  AllocationWriterInventoryEntry,
} from './inventory';

const CANONICAL_TASK_START: EvidenceRequirement[] = [
  {
    kind: 'anyCall',
    names: [
      'resolveTaskStartPlacement',
      'resolveTaskStartPlacementCredentialAttribution',
      'resolveTaskStartPlacementCredentialAttributionFromPlacement',
    ],
    scope: 'module',
  },
  {
    kind: 'anyCall',
    names: ['startTaskRunnerDO', 'ensureTaskRunnerStarted'],
    scope: 'module',
  },
];

export const ALLOCATION_WRITER_INVENTORY: readonly AllocationWriterInventoryEntry[] = [
  {
    filePath: 'apps/api/src/routes/tasks/submit.ts',
    table: 'tasks',
    owner: 'post /submit',
    role: 'user task submit route adapter',
    canonicalService: 'resolveTaskStartPlacement -> startTaskRunnerDO',
    requiredEvidence: CANONICAL_TASK_START,
  },
  {
    filePath: 'apps/api/src/routes/mcp/dispatch-tool.ts',
    table: 'tasks',
    owner: 'handleDispatchTask',
    role: 'MCP dispatch route adapter',
    canonicalService: 'resolveTaskStartPlacement -> startTaskRunnerDO',
    requiredEvidence: CANONICAL_TASK_START,
  },
  {
    filePath: 'apps/api/src/routes/mcp/orchestration-tools.ts',
    table: 'tasks',
    owner: 'handleRetrySubtask',
    role: 'MCP orchestration retry adapter',
    canonicalService: 'resolveTaskStartPlacement -> startTaskRunnerDO',
    requiredEvidence: CANONICAL_TASK_START,
  },
  {
    filePath: 'apps/api/src/services/trigger-submit.ts',
    table: 'tasks',
    owner: 'submitTriggeredTask',
    role: 'trigger submission adapter',
    canonicalService: 'resolveTaskStartPlacement -> startTaskRunnerDO',
    requiredEvidence: CANONICAL_TASK_START,
  },
  {
    filePath: 'apps/api/src/durable-objects/sam-session/tools/dispatch-task.ts',
    table: 'tasks',
    owner: 'dispatchTask',
    role: 'SAM session dispatch tool adapter',
    canonicalService: 'resolveTaskStartPlacement -> startTaskRunnerDO',
    requiredEvidence: CANONICAL_TASK_START,
  },
  {
    filePath: 'apps/api/src/durable-objects/sam-session/tools/retry-subtask.ts',
    table: 'tasks',
    owner: 'retrySubtask',
    role: 'SAM session subtask retry adapter',
    canonicalService: 'resolveTaskStartPlacement -> startTaskRunnerDO',
    requiredEvidence: CANONICAL_TASK_START,
  },
  {
    filePath: 'apps/api/src/services/session-recovery.ts',
    table: 'tasks',
    owner: 'createRecoveryTask',
    role: 'sleeping session wake recovery adapter',
    canonicalService: 'resolveTaskStartPlacement -> startTaskRunnerDO',
    requiredEvidence: CANONICAL_TASK_START,
  },
  {
    filePath: 'apps/api/src/routes/workspaces/workspace-create.ts',
    table: 'tasks',
    owner: 'post /',
    role: 'legacy direct workspace conversation task adapter',
    canonicalService: 'explicit legacy workspace route adapter',
    requiredEvidence: [
      { kind: 'call', name: 'createNodeRecord' },
      { kind: 'call', name: 'provisionNode' },
    ],
  },
  {
    filePath: 'apps/api/src/routes/tasks/crud.ts',
    table: 'tasks',
    owner: 'post /',
    role: 'task metadata CRUD adapter',
    canonicalService: 'explicit non-running task creation adapter',
  },
  {
    filePath: 'apps/api/src/routes/chat.ts',
    table: 'tasks',
    owner: 'post /',
    role: 'conversation task compatibility adapter',
    canonicalService: 'explicit chat task adapter',
  },
  {
    filePath: 'apps/api/src/routes/chat-start.ts',
    table: 'tasks',
    owner: 'post /start',
    role: 'conversation start compatibility adapter',
    canonicalService: 'explicit chat-start task adapter',
  },
  {
    filePath: 'apps/api/src/routes/mcp/idea-tools.ts',
    table: 'tasks',
    owner: 'handleCreateIdea',
    role: 'MCP idea task materialization adapter',
    canonicalService: 'explicit idea adapter',
  },
  {
    filePath: 'apps/api/src/durable-objects/sam-session/tools/create-idea.ts',
    table: 'tasks',
    owner: 'createIdea',
    role: 'SAM session idea task materialization adapter',
    canonicalService: 'explicit idea adapter',
  },
  {
    filePath: 'apps/api/src/services/debug-agent.ts',
    table: 'tasks',
    owner: 'saveDebugDiagnosisAsIdea',
    role: 'debug diagnosis task adapter',
    canonicalService: 'explicit diagnostic adapter',
  },
  {
    filePath: 'apps/api/src/services/platform-feedback-triage/runner.ts',
    table: 'tasks',
    owner: 'runPlatformFeedbackTriage',
    role: 'platform feedback triage task adapter',
    canonicalService: 'explicit feedback adapter',
  },
  {
    filePath: 'apps/api/src/services/platform-feedback-incidents/user-report.ts',
    table: 'tasks',
    owner: 'upsertUserReportIncident',
    role: 'platform feedback incident task adapter',
    canonicalService: 'explicit feedback adapter',
  },
  {
    filePath: 'apps/api/src/services/trial/trial-runner.ts',
    table: 'tasks',
    owner: 'startDiscoveryAgent',
    role: 'trial orchestration task adapter',
    canonicalService: 'explicit trial runtime adapter',
  },
  {
    filePath: 'apps/api/src/services/session-task-repair.ts',
    table: 'tasks',
    owner: 'ensureSessionTaskBacked',
    role: 'session task repair adapter',
    canonicalService: 'explicit repair adapter',
  },
  {
    filePath: 'apps/api/src/services/nodes.ts',
    table: 'nodes',
    owner: 'createNodeRecord',
    role: 'canonical node row writer',
    canonicalService: 'createNodeRecord',
    requiredEvidence: [
      { kind: 'export', name: 'createNodeRecord' },
      { kind: 'call', name: 'capacityPlacementSnapshotDbValues' },
    ],
  },
  {
    filePath: 'apps/api/src/routes/workspaces/workspace-create.ts',
    table: 'workspaces',
    owner: 'post /',
    role: 'legacy direct workspace route adapter',
    canonicalService: 'explicit legacy workspace route adapter',
    requiredEvidence: [{ kind: 'call', name: 'assertNodeAllocationPlanCurrent' }],
  },
  {
    filePath: 'apps/api/src/services/instant-session.ts',
    table: 'workspaces',
    owner: 'acceptInstantSession',
    role: 'Cloudflare container instant runtime adapter',
    canonicalService: 'explicit cf-container runtime adapter',
    requiredEvidence: [{ kind: 'property', name: 'runtime', value: 'cf-container' }],
  },
  {
    filePath: 'apps/api/src/services/workspace-placement.ts',
    table: 'workspaces',
    owner: 'reserveWorkspacePlacement',
    role: 'canonical final workspace placement writer',
    canonicalService: 'reserveWorkspacePlacement',
    requiredEvidence: [
      { kind: 'export', name: 'reserveWorkspacePlacement' },
      { kind: 'call', name: 'capacityPlacementSnapshotSqlValues' },
    ],
  },
  {
    filePath: 'apps/api/src/services/compute-usage.ts',
    table: 'compute_usage',
    owner: 'startComputeTracking',
    role: 'canonical compute metering row writer',
    canonicalService: 'startComputeTracking',
    requiredEvidence: [
      { kind: 'export', name: 'startComputeTracking' },
      { kind: 'property', name: 'providerInstanceVcpuCount' },
    ],
  },
] as const;

export const ALLOCATION_ENTRYPOINT_INVENTORY: readonly AllocationEntrypointInventoryEntry[] = [
  {
    filePath: 'apps/api/src/services/node-provisioning.ts',
    owner: 'provisionNode',
    entrypoint: 'createVM',
    scope: 'service',
    role: 'workspace',
    admission:
      'canonical paid VM boundary validates current node allocation authority and applies the persisted native plan before provider allocation',
    status: 'canonical',
    requiredEvidence: [
      { kind: 'call', name: 'assertNodeAllocationPlanCurrent' },
      { kind: 'call', name: 'applyNativePlanToVmConfig' },
    ],
  },
  {
    filePath: 'apps/api/src/routes/workspaces/workspace-create.ts',
    owner: 'post /',
    entrypoint: 'reserveWorkspacePlacement',
    scope: 'route',
    role: 'workspace',
    admission:
      'direct workspace route delegates its final atomic reservation to the canonical capacity and authority boundary',
    status: 'canonical',
  },
  {
    filePath: 'apps/api/src/durable-objects/trial-orchestrator/steps.ts',
    owner: 'handleWorkspaceCreation',
    entrypoint: 'reserveWorkspacePlacement',
    scope: 'trial-orchestrator',
    role: 'trial',
    admission:
      'trial workspace creation delegates its final atomic reservation to the canonical capacity and authority boundary',
    status: 'canonical',
  },
  {
    filePath: 'apps/api/src/durable-objects/task-runner/node-provisioning-step.ts',
    owner: 'handleNodeProvisioning',
    entrypoint: 'createNodeRecord',
    scope: 'task-runner',
    role: 'workspace',
    admission:
      'recovery authority + VM provisioning admission lease revalidated at the allocation boundary',
    status: 'canonical',
    requiredEvidence: [
      { kind: 'call', name: 'assertVmProvisioningLease' },
      { kind: 'call', name: 'assertRecoveryAuthority' },
    ],
  },
  {
    filePath: 'apps/api/src/durable-objects/task-runner/node-provisioning-step.ts',
    owner: 'handleNodeProvisioning',
    entrypoint: 'provisionNode',
    scope: 'task-runner',
    role: 'workspace',
    admission: 'same lease-guarded provisioning loop as the node record it provisions',
    status: 'canonical',
    requiredEvidence: [{ kind: 'call', name: 'assertVmProvisioningLease' }],
  },
  {
    filePath: 'apps/api/src/durable-objects/task-runner/workspace-steps.ts',
    owner: 'createAndProvisionWorkspace',
    entrypoint: 'reserveWorkspacePlacement',
    scope: 'task-runner',
    role: 'workspace',
    admission: 'canonical atomic placement reservation',
    status: 'canonical',
  },
  {
    filePath: 'apps/api/src/durable-objects/task-runner/workspace-steps.ts',
    owner: 'createWorkspaceOnVmAgent',
    entrypoint: 'createWorkspaceOnNode',
    scope: 'task-runner',
    role: 'workspace',
    admission: 'runtime creation for an already reserved placement',
    status: 'runtime-dispatch',
  },
  {
    filePath: 'apps/api/src/durable-objects/task-runner/workspace-steps.ts',
    owner: 'startComputeTrackingBestEffort',
    entrypoint: 'startComputeTracking',
    scope: 'task-runner',
    role: 'metering',
    admission: 'metering for an already reserved placement',
    status: 'canonical',
  },
  {
    filePath: 'apps/api/src/routes/nodes.ts',
    owner: 'post /',
    entrypoint: 'createNodeRecord',
    scope: 'route',
    role: 'workspace',
    admission:
      'canonical VM allocation plan selects current pool/source/credential authority; node creation persists its snapshot for paid-boundary revalidation',
    status: 'role-adapter',
    requiredEvidence: [{ kind: 'call', name: 'resolveCanonicalVmAllocationPlan' }],
  },
  {
    filePath: 'apps/api/src/routes/nodes.ts',
    owner: 'post /',
    entrypoint: 'provisionNode',
    scope: 'route',
    role: 'workspace',
    admission:
      'provisionNode revalidates the persisted canonical allocation plan at the paid provider boundary; the route does not hold a provisioning lease',
    status: 'role-adapter',
    requiredEvidence: [{ kind: 'call', name: 'resolveCanonicalVmAllocationPlan' }],
  },
  {
    filePath: 'apps/api/src/routes/workspaces/workspace-create.ts',
    owner: 'post /',
    entrypoint: 'createNodeRecord',
    scope: 'route',
    role: 'workspace',
    admission:
      'fresh node uses the canonical VM allocation plan, and workspace creation passes through the final atomic reservation',
    status: 'role-adapter',
    requiredEvidence: [
      { kind: 'call', name: 'resolveCanonicalVmAllocationPlan' },
      { kind: 'call', name: 'reserveWorkspacePlacement' },
    ],
  },
  {
    filePath: 'apps/api/src/routes/workspaces/workspace-create.ts',
    owner: 'post /',
    entrypoint: 'provisionNode',
    scope: 'route',
    role: 'workspace',
    admission:
      'provisionNode revalidates the persisted canonical allocation plan for the node whose workspace was atomically reserved',
    status: 'role-adapter',
    requiredEvidence: [{ kind: 'call', name: 'reserveWorkspacePlacement', scope: 'module' }],
  },
  {
    filePath: 'apps/api/src/routes/workspaces/workspace-create-helpers.ts',
    owner: 'startComputeTrackingForNode',
    entrypoint: 'startComputeTracking',
    scope: 'route',
    role: 'metering',
    admission: 'metering for the legacy direct workspace route',
    status: 'runtime-dispatch',
  },
  {
    filePath: 'apps/api/src/routes/workspaces/_helpers.ts',
    owner: 'scheduleWorkspaceCreateOnNode',
    entrypoint: 'createWorkspaceOnNode',
    scope: 'route',
    role: 'workspace',
    admission: 'runtime creation for a workspace row the route already reserved',
    status: 'runtime-dispatch',
  },
  {
    filePath: 'apps/api/src/routes/node-lifecycle.ts',
    owner: 'post /:id/ready',
    entrypoint: 'createWorkspaceOnNode',
    scope: 'route',
    role: 'workspace',
    admission:
      're-dispatch of already reserved `creating`/undispatched workspaces on a node that just reported ready; allocates no new capacity',
    status: 'runtime-dispatch',
  },
  {
    filePath: 'apps/api/src/services/deployment-provisioning.ts',
    owner: 'provisionDeploymentNode',
    entrypoint: 'createNodeRecord',
    scope: 'service',
    role: 'deployment',
    admission:
      'explicit deployment role adapter with its own concurrent-placement guard; does not take the shared VM provisioning admission lease',
    status: 'role-adapter',
    requiredEvidence: [{ kind: 'property', name: 'nodeRole', value: 'deployment' }],
  },
  {
    filePath: 'apps/api/src/services/deployment-provisioning.ts',
    owner: 'provisionDeploymentNode',
    entrypoint: 'provisionNode',
    scope: 'service',
    role: 'deployment',
    admission: 'paid provisioning of the deployment-role node created above',
    status: 'role-adapter',
  },
  {
    filePath: 'apps/api/src/services/session-snapshot-upload-relay.ts',
    owner: 'ensureSessionSnapshotUploadRelay',
    entrypoint: 'createNodeRecord',
    scope: 'service',
    role: 'recovery-relay',
    admission:
      'relay uses a fresh canonical VM allocation plan and persists its current pool/source/credential snapshot; it does not copy source-node authority',
    status: 'role-adapter',
    requiredEvidence: [{ kind: 'call', name: 'resolveCanonicalVmAllocationPlan', scope: 'module' }],
  },
  {
    filePath: 'apps/api/src/services/session-snapshot-upload-relay.ts',
    owner: 'ensureSessionSnapshotUploadRelay',
    entrypoint: 'provisionNode',
    scope: 'service',
    role: 'recovery-relay',
    admission:
      'paid provisioning checks the canonical node plan and caller-supplied source/session relay authority, with scoped compensation after a fresh allocation fails',
    status: 'role-adapter',
    requiredEvidence: [{ kind: 'call', name: 'assertRelayProvisioningAuthority' }],
  },
  {
    filePath: 'apps/api/src/services/instant-session.ts',
    owner: 'acceptInstantSession',
    entrypoint: 'createNodeRecord',
    scope: 'service',
    role: 'instant',
    admission:
      'Cloudflare container runtime record; allocates no VM capacity, so the VM admission lease does not apply',
    status: 'runtime-adapter',
    requiredEvidence: [{ kind: 'property', name: 'runtime', value: 'cf-container' }],
  },
  {
    filePath: 'apps/api/src/services/instant-session.ts',
    owner: 'continueInstantSessionLaunch',
    entrypoint: 'createWorkspaceOnNode',
    scope: 'service',
    role: 'instant',
    admission: 'runtime creation for an already accepted instant session',
    status: 'runtime-dispatch',
  },
  {
    filePath: 'apps/api/src/durable-objects/trial-orchestrator/steps.ts',
    owner: 'handleNodeProvisioning',
    entrypoint: 'createNodeRecord',
    scope: 'trial-orchestrator',
    role: 'trial',
    admission:
      'single-node-per-trial state guard on the platform credential; no capacity-pool selection or admission lease',
    status: 'runtime-adapter',
  },
  {
    filePath: 'apps/api/src/durable-objects/trial-orchestrator/steps.ts',
    owner: 'handleNodeProvisioning',
    entrypoint: 'provisionNode',
    scope: 'trial-orchestrator',
    role: 'trial',
    admission: 'paid provisioning of the trial node created above',
    status: 'runtime-adapter',
  },
  {
    filePath: 'apps/api/src/durable-objects/trial-orchestrator/steps.ts',
    owner: 'handleWorkspaceCreation',
    entrypoint: 'createWorkspaceOnNode',
    scope: 'trial-orchestrator',
    role: 'trial',
    admission: 'runtime creation for the trial workspace row reserved in the same step',
    status: 'runtime-dispatch',
  },
] as const;
