/**
 * Shared types and utilities for ProjectData DO modules.
 */

import type { VmAgentContainer } from '../vm-agent-container';

export type Env = {
  DATABASE: D1Database;
  NOTIFICATION?: DurableObjectNamespace;
  KV: KVNamespace;
  VM_AGENT_CONTAINER?: DurableObjectNamespace<VmAgentContainer>;
  NODE_HEARTBEAT_STALE_SECONDS?: string;
  TASK_LIVENESS_MAX_ACP_SESSIONS?: string;
  TASK_LIVENESS_PROBE_TIMEOUT_MS?: string;
  IDLE_CLEANUP_MAX_CANDIDATES_PER_SWEEP?: string;
  BASE_DOMAIN?: string;
  DO_SUMMARY_SYNC_DEBOUNCE_MS?: string;
  MAX_SESSIONS_PER_PROJECT?: string;
  MAX_MESSAGES_PER_SESSION?: string;
  DOCUMENT_CARD_RAW_OUTPUT_MAX_BYTES?: string;
  ACTIVITY_RETENTION_DAYS?: string;
  SESSION_IDLE_TIMEOUT_MINUTES?: string;
  IDLE_CLEANUP_RETRY_DELAY_MS?: string;
  IDLE_CLEANUP_MAX_RETRIES?: string;
  ACP_SESSION_DETECTION_WINDOW_MS?: string;
  ACP_SESSION_MAX_FORK_DEPTH?: string;
  WORKSPACE_IDLE_TIMEOUT_MS?: string;
  KNOWLEDGE_MAX_ENTITIES_PER_PROJECT?: string;
  KNOWLEDGE_MAX_OBSERVATIONS_PER_ENTITY?: string;
  MAILBOX_ACK_TIMEOUT_MS?: string;
  MAILBOX_REDELIVERY_MAX_ATTEMPTS?: string;
  MAILBOX_TTL_MS?: string;
  MAILBOX_DELIVERY_POLL_INTERVAL_MS?: string;
  MAILBOX_MAX_MESSAGES_PER_PROJECT?: string;
  POLICY_MAX_PER_PROJECT?: string;
  HUMAN_INPUT_TIMEOUT_MS?: string;
  HUMAN_INPUT_ESCALATION_FRACTIONS?: string;
  HUMAN_INPUT_UNDELIVERED_GRACE_MS?: string;
  HUMAN_INPUT_MAX_WAIT_MS?: string;
  TASK_RECONCILIATION_IDLE_MS?: string;
  TASK_RECONCILIATION_RESPONSE_DEADLINE_MS?: string;
  TASK_RECONCILIATION_PROMPT_SOFT_STALL_MS?: string;
  TASK_RECONCILIATION_PROMPT_HARD_STALL_MS?: string;
  TASK_RECONCILIATION_MIN_ALARM_DELAY_MS?: string;
  SESSION_ACTIVITY_STALE_THRESHOLD_MS?: string;
  DO_ALARMS_ENABLED_KV_KEY?: string;
  CONTROL_LOOP_KILL_SWITCH_CACHE_MS?: string;
  CONTROL_LOOP_DISABLED_ALARM_RETRY_MS?: string;
  DURABLE_PROMPT_DELIVERY_ENABLED?: string;
  PROMPT_DELIVERY_LEGACY_VM_COMPAT_ENABLED?: string;
  PROMPT_DELIVERY_MAX_CANDIDATES_PER_ALARM?: string;
  PROMPT_DELIVERY_MAX_ATTEMPTS?: string;
  PROMPT_DELIVERY_RETRY_BASE_MS?: string;
  PROMPT_DELIVERY_RETRY_MAX_MS?: string;
  PROMPT_DELIVERY_TTL_MS?: string;
  PROMPT_DELIVERY_RECEIPT_TIMEOUT_MS?: string;
  PROMPT_DELIVERY_BACKGROUND_TIMEOUT_MS?: string;
  PROMPT_DELIVERY_MIN_ALARM_DELAY_MS?: string;
  ACP_LONG_TURN_SUPERVISOR_ENABLED?: string;
  ACP_LONG_TURN_CHECKPOINT_MS?: string;
  ACP_CHECKPOINT_PREEMPT_GRACE_MS?: string;
};

export interface SummaryData {
  lastActivityAt: string;
  activeSessionCount: number;
}

export function generateId(): string {
  return crypto.randomUUID();
}
