/** Deployment-overridable protocol bounds; user-facing policy lives in Connector settings. */
export const MIN_CONNECTOR_RESPONSE_MAX_BYTES = 256;
export const DEFAULT_CONNECTOR_RESPONSE_MAX_BYTES = 120_000;
export const DEFAULT_CONNECTOR_REQUEST_MAX_BYTES = 256 * 1024;
export const DEFAULT_CONNECTOR_OAUTH_REQUEST_MAX_BYTES = 16_384;
export const DEFAULT_CONNECTOR_REGISTRATION_PER_IP_PER_HOUR = 20;
export const DEFAULT_CONNECTOR_REGISTRATION_GLOBAL_PER_HOUR = 100;
export const DEFAULT_CONNECTOR_CLIENT_IDLE_TTL_SECONDS = 7_776_000;
export const DEFAULT_CONNECTOR_CLIENT_NAME_MAX_LENGTH = 200;
export const DEFAULT_CONNECTOR_REDIRECT_URI_MAX_COUNT = 10;
