import * as v from 'valibot';

// Mirrors the Completion/ToolCall interfaces in debug-agent.ts field-for-field
// — every field the model's chat-completion response can populate is already
// read through optional chaining downstream (completion.choices?.[0]?.message,
// completion.usage?.prompt_tokens, ...), so this validates *shape* rather
// than tightening what a well-formed response looks like.
const toolCallSchema = v.object({
  id: v.string(),
  type: v.literal('function'),
  function: v.object({
    name: v.string(),
    arguments: v.string(),
  }),
});

export const completionSchema = v.object({
  choices: v.optional(
    v.array(
      v.object({
        message: v.optional(
          v.object({
            content: v.optional(v.nullable(v.string())),
            tool_calls: v.optional(v.array(toolCallSchema)),
          })
        ),
      })
    )
  ),
  usage: v.optional(
    v.object({
      prompt_tokens: v.optional(v.number()),
      completion_tokens: v.optional(v.number()),
      total_tokens: v.optional(v.number()),
    })
  ),
});

// query_cloudflare_logs tool-call arguments, generated by the debugging
// model itself. Untrusted-shaped input degrades to the same `{}` bounded
// defaults as a JSON syntax error — see parseDebugToolArgs() below.
const debugToolArgsSchema = v.object({
  search: v.optional(v.string()),
  levels: v.optional(v.array(v.string())),
});

/**
 * Parses `query_cloudflare_logs` tool-call arguments emitted by the
 * debugging model itself. A syntactically valid but wrongly-shaped payload
 * (e.g. non-string search) falls through to the same bounded `{}` defaults
 * as a JSON syntax error, instead of a blind cast handing a mistyped value
 * to queryCloudflareLogs.
 */
export function parseDebugToolArgs(argumentsJson: string): {
  search?: string;
  levels?: string[];
} {
  let args: { search?: string; levels?: string[] } = {};
  try {
    const parsed = JSON.parse(argumentsJson) as unknown;
    const validated = v.safeParse(debugToolArgsSchema, parsed);
    if (validated.success) args = validated.output;
  } catch {
    /* bounded defaults */
  }
  return args;
}
