/** Environment configuration consumed by generic webhook trigger surfaces. */
export interface WebhookTriggerEnv {
  WEBHOOK_TRIGGERS_ENABLED?: string;
  WEBHOOK_TRIGGER_MAX_BODY_BYTES?: string;
  WEBHOOK_TRIGGER_MAX_FILTERS?: string;
  WEBHOOK_TRIGGER_MAX_FILTER_PATH_LENGTH?: string;
  WEBHOOK_TRIGGER_MAX_FILTER_PATH_DEPTH?: string;
  WEBHOOK_TRIGGER_MAX_INCLUDED_HEADERS?: string;
  WEBHOOK_TRIGGER_MAX_IDEMPOTENCY_KEY_LENGTH?: string;
  WEBHOOK_TRIGGER_RATE_LIMIT_PER_MINUTE?: string;
  WEBHOOK_INVALID_TOKEN_RATE_LIMIT_PER_MINUTE?: string;
  WEBHOOK_RATE_LIMIT_WINDOW_SECONDS?: string;
  WEBHOOK_DELIVERY_RETENTION_DAYS?: string;
}
