/** Environment configuration consumed by generic webhook trigger surfaces. */
export interface WebhookTriggerEnv {
  WEBHOOK_TRIGGERS_ENABLED?: string;
  WEBHOOK_TRIGGER_MAX_BODY_BYTES?: string;
  WEBHOOK_TRIGGER_MAX_FILTERS?: string;
  WEBHOOK_TRIGGER_MAX_FILTER_PATH_LENGTH?: string;
  WEBHOOK_TRIGGER_MAX_FILTER_PATH_DEPTH?: string;
  WEBHOOK_TRIGGER_MAX_INCLUDED_HEADERS?: string;
  WEBHOOK_TRIGGER_MAX_HEADER_NAME_LENGTH?: string;
  WEBHOOK_TRIGGER_MAX_SOURCE_LABEL_LENGTH?: string;
  WEBHOOK_TRIGGER_MAX_IDEMPOTENCY_KEY_LENGTH?: string;
  WEBHOOK_TRIGGER_RATE_LIMIT_PER_MINUTE?: string;
  WEBHOOK_INVALID_TOKEN_RATE_LIMIT_PER_MINUTE?: string;
  WEBHOOK_INGRESS_RATE_LIMIT_PER_MINUTE?: string;
  WEBHOOK_RATE_LIMIT_WINDOW_SECONDS?: string;
  WEBHOOK_DELIVERY_RETENTION_DAYS?: string;
  WEBHOOK_DELIVERY_CLEANUP_BATCH_SIZE?: string;
  WEBHOOK_DELIVERY_DEFAULT_PAGE_SIZE?: string;
  WEBHOOK_DELIVERY_MAX_PAGE_SIZE?: string;
  WEBHOOK_DELIVERY_PROCESSING_LEASE_SECONDS?: string;
}
