package acp

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"strings"
)

// vibeDefaultActiveModel is the model alias used when no user model override
// is configured. Defaults to Mistral Large (their most capable model).
// Override at deployment via VIBE_DEFAULT_ACTIVE_MODEL env var.
var vibeDefaultActiveModel = func() string {
	if v := os.Getenv("VIBE_DEFAULT_ACTIVE_MODEL"); v != "" {
		return v
	}
	return "mistral-large"
}()

// sanitizeVibeModelAlias validates and sanitizes a model alias string to
// prevent TOML injection. Aliases must be alphanumeric with hyphens only.
// Returns the sanitized alias, or the default if the input is invalid.
func sanitizeVibeModelAlias(alias string) string {
	if alias == "" {
		return vibeDefaultActiveModel
	}
	for _, c := range alias {
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.') {
			slog.Warn("Invalid Vibe model alias, falling back to default",
				"requested", alias, "default", vibeDefaultActiveModel)
			return vibeDefaultActiveModel
		}
	}
	return alias
}

// vibeBuiltinAliases lists the aliases that are always defined in the
// generated config. If the user selects one of these, no extra entry is needed.
var vibeBuiltinAliases = map[string]bool{
	"mistral-large": true,
	"devstral-2":    true,
	"codestral":     true,
}

// generateVibeConfig produces a TOML config for ~/.vibe/config.toml that
// defines model aliases so users can select models beyond the built-in
// defaults. The activeModel parameter sets which alias is active.
// If activeModel doesn't match a built-in alias, a dynamic [[models]] entry
// is generated using the value as both the alias and the Mistral API model name.
// This allows the UI model catalog to use raw Mistral API IDs without needing
// vm-agent changes when new models are released.
// If mcpServers is provided, it includes MCP server configurations for tool discovery.
func generateVibeConfig(activeModel string, mcpServers []McpServerEntry) string {
	activeModel = sanitizeVibeModelAlias(activeModel)

	config := fmt.Sprintf(`# Generated by SAM vm-agent — do not edit manually.
# This config defines model aliases and MCP servers for Mistral Vibe ACP sessions.

active_model = "%s"

# Mistral Large — most capable model
[[models]]
name = "mistral-large-latest"
provider = "mistral"
alias = "mistral-large"
temperature = 0.2

# Devstral 2 — default coding model
[[models]]
name = "mistral-vibe-cli-latest"
provider = "mistral"
alias = "devstral-2"
temperature = 0.2

# Codestral — code-specialized model
[[models]]
name = "codestral-latest"
provider = "mistral"
alias = "codestral"
temperature = 0.2
`, activeModel)

	// If the active model isn't a built-in alias, generate a dynamic entry
	// using the model ID as both alias and API name. This lets the UI catalog
	// list raw Mistral API model IDs (e.g. "mistral-medium-3-5-2604") without
	// requiring vm-agent updates for each new model.
	if activeModel != vibeDefaultActiveModel && !vibeBuiltinAliases[activeModel] {
		config += fmt.Sprintf(`
# Dynamic model entry (from SAM user settings)
[[models]]
name = "%s"
provider = "mistral"
alias = "%s"
temperature = 0.2
`, activeModel, activeModel)
	}

	// Append MCP server configurations if provided.
	//
	// Names come from the shared resolver rather than a local "sam-mcp-%d" — this call site
	// used to always index-suffix, so a single server was named "sam-mcp-0" here while ACP
	// and Codex called the same server "sam-mcp". Using the shared resolver fixes that
	// divergence as well as honouring user-chosen names.
	names := ResolveMcpServerNames(mcpServers)
	for i, server := range mcpServers {
		// Skip entries with control characters that would corrupt TOML
		if strings.ContainsAny(server.URL, "\n\r") || strings.ContainsAny(server.Token, "\n\r") {
			slog.Warn("Skipping MCP server with control characters in URL or token",
				"index", i, "url_length", len(server.URL))
			continue
		}
		safeURL := tomlEscapeBasicString(server.URL)
		config += fmt.Sprintf("\n[[mcp_servers]]\nname = \"%s\"\ntransport = \"http\"\nurl = \"%s\"\n", names[i], safeURL)
		if server.Token != "" {
			safeToken := tomlEscapeBasicString(server.Token)
			config += fmt.Sprintf("headers = { Authorization = \"Bearer %s\" }\n", safeToken)
		}
	}

	return config
}

// resolveVibeActiveModel determines which model alias to use for a Mistral
// Vibe session. Returns the user's model override if set, otherwise the
// platform default (Mistral Large).
func resolveVibeActiveModel(settings *agentSettingsPayload) string {
	if settings != nil && settings.Model != "" {
		return settings.Model
	}
	return vibeDefaultActiveModel
}

// writeVibeConfigToContainer writes a .vibe/config.toml into the container
// for the Mistral Vibe agent. This is necessary because VIBE_ACTIVE_MODEL
// expects a config alias (not a raw API model name), and only "devstral-2"
// is defined by default. If mcpServers is provided, it includes MCP server
// configurations for tool discovery.
func writeVibeConfigToContainer(ctx context.Context, containerID, user, activeModel string, mcpServers []McpServerEntry) error {
	config := generateVibeConfig(activeModel, mcpServers)
	return writeAuthFileToContainer(ctx, containerID, user, ".vibe/config.toml", config)
}
